name: debug_app_web
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.6.0
  baby_package:
    path: /home/ansh/Studio Projects/Clone/baby_package
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  collection: ^1.19.0
  connectivity_plus: ^6.1.4
  dartz: ^0.10.1
  desktop_lifecycle: ^0.1.1
  desktop_multi_window: ^0.2.1
  device_info_plus: ^11.3.0
  equatable: ^2.0.7
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.2
  flutter_lints: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  heroicons: ^0.11.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hugeicons: ^0.0.7
  intl: ^0.20.2
  json_annotation: ^4.6.0
  logger: ^2.5.0
  lottie: ^3.3.1
  lucide_icons_flutter: ^3.0.2
  multi_split_view: ^3.6.0
  network_info_plus: ^6.1.2
  package_info_plus: ^8.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  provider: ^6.1.5
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  stack_trace: ^1.12.0
  storybook_flutter: ^0.14.1
  theme_ui_widgets:
    path: package/theme_ui_widgets
  toastification:
    path: package/toastification-main
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.15
  device_preview: ^1.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.0
  lints: ^5.1.1
  mocktail: ^1.0.4
  test: ^1.24.3
  very_good_analysis: ^7.0.0
  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
